export const areas = [
  {
    slug: 'windsor',
    name: 'Windsor',
    county: 'Berkshire',
    intro: 'RVS Bespoke is based in Windsor — our workshop is here, and so are many of the homes we work in. From period properties on the Long Walk to modern new builds near the river, we design and build fitted furniture that suits every style of home Windsor has to offer.',
    postcode: 'SL4',
    nearby: ['Eton', 'Datchet', 'Old Windsor', 'Clewer'],
  },
  {
    slug: 'ascot',
    name: 'Ascot',
    county: 'Berkshire',
    intro: "Ascot is home to some of Berkshire's finest properties, and our fitted furniture reflects that. Whether you're fitting out a large family home or a converted stable, we bring the same level of craftsmanship and attention to detail to every project in the area.",
    postcode: 'SL5',
    nearby: ['Sunningdale', 'Sunninghill', 'Cheapside', 'North Ascot'],
  },
  {
    slug: 'maidenhead',
    name: 'Maidenhead',
    county: 'Berkshire',
    intro: 'From riverside homes along the Thames to family houses in the town centre, RVS Bespoke has fitted furniture for kitchens, bedrooms, and living rooms across Maidenhead. Every piece is made to measure in our Windsor workshop and installed by our own team.',
    postcode: 'SL6',
    nearby: ['Cookham', 'Taplow', 'Bray', 'White Waltham'],
  },
  {
    slug: 'slough',
    name: 'Slough',
    county: 'Berkshire',
    intro: "Slough's mix of Victorian terraces, 1930s semis, and newer developments means no two rooms are the same — which is exactly why bespoke fitted furniture works so well here. We design around your specific space, not around standard box sizes.",
    postcode: 'SL1',
    nearby: ['Langley', 'Burnham', 'Farnham Royal', 'Cippenham'],
  },
  {
    slug: 'eton',
    name: 'Eton',
    county: 'Berkshire',
    intro: "Eton's historic character calls for furniture built with real care and quality. We work with the proportions and period details of older homes here, creating fitted pieces that look as though they were always part of the building.",
    postcode: 'SL4',
    nearby: ['Windsor', 'Eton Wick', 'Clewer Green', 'Datchet'],
  },
  {
    slug: 'sunningdale',
    name: 'Sunningdale',
    county: 'Berkshire',
    intro: "Sunningdale's large detached homes and golf course properties are a natural fit for premium bespoke joinery. We design fitted furniture that matches the scale and quality of the homes here — from grand dressing rooms to bespoke home offices and media walls.",
    postcode: 'SL5',
    nearby: ['Ascot', 'Virginia Water', 'Sunninghill', 'Windlesham'],
  },
  {
    slug: 'datchet',
    name: 'Datchet',
    county: 'Berkshire',
    intro: 'A short drive from our Windsor workshop, Datchet is one of the villages we visit regularly. We install fitted furniture for bedrooms, kitchens, and living rooms in Datchet homes and are familiar with the mix of property styles in the area.',
    postcode: 'SL3',
    nearby: ['Windsor', 'Horton', 'Wraysbury', 'Colnbrook'],
  },
  {
    slug: 'virginia-water',
    name: 'Virginia Water',
    county: 'Surrey',
    intro: "Virginia Water is one of the most sought-after addresses in the south east, and we regularly work on projects here. Large homes with high ceilings and generous room sizes suit our approach — every piece is designed to fill the space perfectly and built to the standard the area expects.",
    postcode: 'GU25',
    nearby: ['Sunningdale', 'Wentworth', 'Egham', 'Thorpe'],
  },
  {
    slug: 'wokingham',
    name: 'Wokingham',
    county: 'Berkshire',
    intro: "Wokingham's growing community of family homes is well served by our fitted furniture. We cover the full range — from fitted bedrooms and wardrobes to home offices and under-stair storage — and bring the same Windsor workshop quality to every project.",
    postcode: 'RG40',
    nearby: ['Winnersh', 'Earley', 'Finchampstead', 'Bracknell'],
  },
  {
    slug: 'bracknell',
    name: 'Bracknell',
    county: 'Berkshire',
    intro: 'Bracknell has seen significant development in recent years, bringing a wide range of home styles that benefit from fitted furniture. We design and install bespoke pieces across Bracknell, from alcove shelving in older properties to full bedroom fits in modern new builds.',
    postcode: 'RG12',
    nearby: ['Sandhurst', 'Crowthorne', 'Warfield', 'Binfield'],
  },
];

export default areas;
